### ISSUE TITLE
Segments on G203

### ISSUE THREAD

**Issue by kokoko3k** [derEisele/G213Colors#7]
I don't know if they are supported by the mouse, but when i try to set them, here is what happens in the terminal:
```
3700
segments
G203
Connected G203
1
000000
Send data to G203
bmRequestType, bmRequest, wValue[productName], wIndex, binascii.unhexlify(data)
33 9 528 1 b'\x11\xff\x0e<\x01\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
2
000000
Send data to G203
bmRequestType, bmRequest, wValue[productName], wIndex, binascii.unhexlify(data)
33 9 528 1 b'\x11\xff\x0e<\x02\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Traceback (most recent call last):
  File "./main.py", line 95, in on_button_clicked
    self.sendManager(product)
  File "./main.py", line 86, in sendManager
    self.sendSegments(product)
  File "./main.py", line 66, in sendSegments
    myG.sendColorCommand(self.btnGetHex(self.segmentColorBtns[i -1]), i)
  File "/home/koko/tmp/G213Colors/G213Colors.py", line 100, in sendColorCommand
    sendData(colorCommand[productName].format(str(format(field, '02x')), colorHex))
  File "/home/koko/tmp/G213Colors/G213Colors.py", line 95, in sendData
    device.ctrl_transfer(bmRequestType, bmRequest, wValue[productName], wIndex, binascii.unhexlify(data))
  File "/usr/lib/python3.5/site-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/lib/python3.5/site-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/usr/lib/python3.5/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error
```

**Comment by dereisele** [comment]
Hello,
The mouse does not support segments. I was just too lazy to add a check whether the device supports this mode or not. Never the less thanks for reminding me of this issue.
